title: "Fayaz Ahmed A Sajan"
email: iamfaztech@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This description is to describe what i can explore, not what i can do.
baseurl: "/" 
url: "https://fayazsajan.github.io/" 
twitter_username: iamfayaz7
github_username:  fayazsajan

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
